<a href="https://colab.research.google.com/github/Omarelfarouk90/operation-research-codes/blob/main/Game_theory_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Credits to Enginer Brandon smith 

Lets start with the prisoner's dilema , we have the following output 



In [ ]:
!pip install quantecon

     |████████████████████████████████| 269 kB 13.2 MB/s 


In [ ]:
import quantecon as qe
# create a list containing both players payoffs
pt = [[(0.45,0.25), (0.60,0.2),(0.6,0.15)],[(0.40,0.30), (0.45,0.25),(0.5,0.15)],[(0.25,0.45), (0.35,0.30),(0.40,0.20)]]
g1 = qe.game_theory.NormalFormGame(pt)
print(g1)

/usr/local/lib/python3.7/dist-packages/numba/np/ufunc/parallel.py:363: NumbaWarning: The TBB threading layer requires TBB version 2019.5 or later i.e., TBB_INTERFACE_VERSION >= 11005. Found TBB_INTERFACE_VERSION = 9107. The TBB threading layer is disabled.
  warnings.warn(problem)


2-player NormalFormGame with payoff profile array:
[[[0.45, 0.25],  [0.6 , 0.2 ],  [0.6 , 0.15]],
 [[0.4 , 0.3 ],  [0.45, 0.25],  [0.5 , 0.15]],
 [[0.25, 0.45],  [0.35, 0.3 ],  [0.4 , 0.2 ]]]


In [ ]:
g1.players[0].payoff_array 

array([[0.45, 0.6 , 0.6 ],
       [0.4 , 0.45, 0.5 ],
       [0.25, 0.35, 0.4 ]])

In [ ]:
def sequential_best_response(g, init_actions=None, tie_breaking='smallest',
                             verbose=True):
    """
    Find a pure Nash equilibrium of a normal form game by sequential best
    response.

    Parameters
    ----------
    g : NormalFormGame

    init_actions : array_like(int), optional(default=[0, ..., 0])
        The initial action profile.

    tie_breaking : {'smallest', 'random'}, optional(default='smallest')

    verbose: bool, optional(default=True)
        If True, print the intermediate process.

    """
    N = g.N  # Number of players
    a = np.empty(N, dtype=int)  # Action profile
    if init_actions is None:
        init_actions = [0] * N
    a[:] = init_actions

    if verbose:
        print('init_actions: {0}'.format(a))

    new_a = np.empty(N, dtype=int)
    max_iter = np.prod(g.nums_actions)

    for t in range(max_iter):
        new_a[:] = a
        for i, player in enumerate(g.players):
            if N == 2:
                a_except_i = new_a[1-i]
            else:
                a_except_i = new_a[np.arange(i+1, i+N) % N]
            new_a[i] = player.best_response(a_except_i,
                                            tie_breaking=tie_breaking)
            if verbose:
                print('player {0}: {1}'.format(i, new_a))
        if np.array_equal(new_a, a):
            return a
        else:
            a[:] = new_a

    print('No pure Nash equilibrium found')
    return None

In [ ]:
import numpy as np
import quantecon.game_theory as gt

In [ ]:
a_star = sequential_best_response(g1)  # By default, start with (0, 0, 0)
print('Nash equilibrium indices: {0}'.format(a_star))


init_actions: [0 0]
player 0: [0 0]
player 1: [0 0]
Nash equilibrium indices: [0 0]


In [ ]:
import quantecon as qe
# create a list containing both players payoffs
pt = [[(50,10), (80,25),(80,30)],[(65,20), (75,35),(85,30)],[(50,50), (70,45),(80,40)]]
g2 = qe.game_theory.NormalFormGame(pt)
print(g2)

2-player NormalFormGame with payoff profile array:
[[[50, 10],  [80, 25],  [80, 30]],
 [[65, 20],  [75, 35],  [85, 30]],
 [[50, 50],  [70, 45],  [80, 40]]]


In [ ]:
g2.players[0].payoff_array 

array([[50, 80, 80],
       [65, 75, 85],
       [50, 70, 80]])

Get Nash Equilibrium

In [ ]:
def sequential_best_response(g, init_actions=None, tie_breaking='smallest',
                             verbose=True):
    """
    Find a pure Nash equilibrium of a normal form game by sequential best
    response.

    Parameters
    ----------
    g : NormalFormGame

    init_actions : array_like(int), optional(default=[0, ..., 0])
        The initial action profile.

    tie_breaking : {'smallest', 'random'}, optional(default='smallest')

    verbose: bool, optional(default=True)
        If True, print the intermediate process.

    """
    N = g.N  # Number of players
    a = np.empty(N, dtype=int)  # Action profile
    if init_actions is None:
        init_actions = [0] * N
    a[:] = init_actions

    if verbose:
        print('init_actions: {0}'.format(a))

    new_a = np.empty(N, dtype=int)
    max_iter = np.prod(g.nums_actions)

    for t in range(max_iter):
        new_a[:] = a
        for i, player in enumerate(g.players):
            if N == 2:
                a_except_i = new_a[1-i]
            else:
                a_except_i = new_a[np.arange(i+1, i+N) % N]
            new_a[i] = player.best_response(a_except_i,
                                            tie_breaking=tie_breaking)
            if verbose:
                print('player {0}: {1}'.format(i, new_a))
        if np.array_equal(new_a, a):
            return a
        else:
            a[:] = new_a

    print('No pure Nash equilibrium found')
    return None

In [ ]:

import numpy as np
import quantecon.game_theory as gt

In [ ]:

a_star = sequential_best_response(g2)  # By default, start with (0, 0, 0)
print('Nash equilibrium indices: {0}'.format(a_star))

init_actions: [0 0]
player 0: [1 0]
player 1: [1 1]
player 0: [0 1]
player 1: [0 2]
player 0: [1 2]
player 1: [1 1]
player 0: [0 1]
player 1: [0 2]
player 0: [1 2]
player 1: [1 1]
player 0: [0 1]
player 1: [0 2]
player 0: [1 2]
player 1: [1 1]
player 0: [0 1]
player 1: [0 2]
player 0: [1 2]
player 1: [1 1]
No pure Nash equilibrium found
Nash equilibrium indices: None


In [ ]:
gt.support_enumeration(g2)

[(array([0.5, 0.5, 0. ]), array([0. , 0.5, 0.5]))]

Question 2 part A


In [ ]:
import quantecon as qe
# create a list containing both players payoffs
pt = [[(-200,0),(-200,0),(-200,0),(-200,0),(-200,0),(-200,0),(-200,0)],
      [(0,-100),(-150,0),(-150,0),(-150,0),(-150,0),(-150,0),(-150,0)],
      [(0,-100),(0,-50),(-100,0),(-100,0),(-100,0),(-100,0),(-100,0)],
      [(0,-100),(0,-50),(0,0),(-50,0),(-50,0),(-50,0),(-50,0)],
      [(0,-100),(0,-50),(0,0),(0,50),(0,0),(0,0),(0,0)],
      [(0,-100),(0,-50),(0,0),(0,50),(0,100),(50,0),(50,0)],
      [(0,-100),(0,-50),(0,0),(0,50),(0,100),(0,150),(100,0)]]
g3 = qe.game_theory.NormalFormGame(pt)
print(g3)

2-player NormalFormGame with payoff profile array:
[[[-200,    0],  [-200,    0],  [-200,    0],  [-200,    0],  [-200,    0],  [-200,    0],  [-200,    0]],
 [[   0, -100],  [-150,    0],  [-150,    0],  [-150,    0],  [-150,    0],  [-150,    0],  [-150,    0]],
 [[   0, -100],  [   0,  -50],  [-100,    0],  [-100,    0],  [-100,    0],  [-100,    0],  [-100,    0]],
 [[   0, -100],  [   0,  -50],  [   0,    0],  [ -50,    0],  [ -50,    0],  [ -50,    0],  [ -50,    0]],
 [[   0, -100],  [   0,  -50],  [   0,    0],  [   0,   50],  [   0,    0],  [   0,    0],  [   0,    0]],
 [[   0, -100],  [   0,  -50],  [   0,    0],  [   0,   50],  [   0,  100],  [  50,    0],  [  50,    0]],
 [[   0, -100],  [   0,  -50],  [   0,    0],  [   0,   50],  [   0,  100],  [   0,  150],  [ 100,    0]]]


In [ ]:
g3.players[0].payoff_array 

array([[-200, -200, -200, -200, -200, -200, -200],
       [   0, -150, -150, -150, -150, -150, -150],
       [   0,    0, -100, -100, -100, -100, -100],
       [   0,    0,    0,  -50,  -50,  -50,  -50],
       [   0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,   50,   50],
       [   0,    0,    0,    0,    0,    0,  100]])

In [ ]:
def sequential_best_response(g, init_actions=None, tie_breaking='smallest',
                             verbose=True):
    """
    Find a pure Nash equilibrium of a normal form game by sequential best
    response.

    Parameters
    ----------
    g : NormalFormGame

    init_actions : array_like(int), optional(default=[0, ..., 0])
        The initial action profile.

    tie_breaking : {'smallest', 'random'}, optional(default='smallest')

    verbose: bool, optional(default=True)
        If True, print the intermediate process.

    """
    N = g.N  # Number of players
    a = np.empty(N, dtype=int)  # Action profile
    if init_actions is None:
        init_actions = [0] * N
    a[:] = init_actions

    if verbose:
        print('init_actions: {0}'.format(a))

    new_a = np.empty(N, dtype=int)
    max_iter = np.prod(g.nums_actions)

    for t in range(max_iter):
        new_a[:] = a
        for i, player in enumerate(g.players):
            if N == 2:
                a_except_i = new_a[1-i]
            else:
                a_except_i = new_a[np.arange(i+1, i+N) % N]
            new_a[i] = player.best_response(a_except_i,
                                            tie_breaking=tie_breaking)
            if verbose:
                print('player {0}: {1}'.format(i, new_a))
        if np.array_equal(new_a, a):
            return a
        else:
            a[:] = new_a

    print('No pure Nash equilibrium found')
    return None

In [ ]:
import numpy as np
import quantecon.game_theory as gt

In [ ]:
a_star = sequential_best_response(g3)  # By default, start with (0, 0, 0)
print('Nash equilibrium indices: {0}'.format(a_star))

init_actions: [0 0]
player 0: [1 0]
player 1: [1 1]
player 0: [2 1]
player 1: [2 2]
player 0: [3 2]
player 1: [3 2]
player 0: [3 2]
player 1: [3 2]
Nash equilibrium indices: [3 2]


In [ ]:
gt.support_enumeration(g3)

[(array([0., 0., 0., 1., 0., 0., 0.]), array([0., 0., 1., 0., 0., 0., 0.])),
 (array([0., 0., 0., 0., 1., 0., 0.]), array([0., 0., 0., 1., 0., 0., 0.])),
 (array([0., 0., 0., 0., 0., 1., 0.]), array([0., 0., 0., 0., 1., 0., 0.]))]

Question 2 part 2

In [ ]:
import quantecon as qe
# create a list containing both players payoffs
pt = [[(-100,-50),(-200,0),(-200,0),(-200,0),(-200,0),(-200,0),(-200,0)],
      [(0,-100),(-75,-25),(-150,0),(-150,0),(-150,0),(-150,0),(-150,0)],
      [(0,-100),(0,-50),(-50,0),(-100,0),(-100,0),(-100,0),(-100,0)],
      [(0,-100),(0,-50),(0,0),(-25,25),(-50,0),(-50,0),(-50,0)],
      [(0,-100),(0,-50),(0,0),(0,50),(0,50),(0,0),(0,0)],
      [(0,-100),(0,-50),(0,0),(0,50),(0,100),(25,75),(50,0)],
      [(0,-100),(0,-50),(0,0),(0,50),(0,100),(0,150),(50,100)]]
g4 = qe.game_theory.NormalFormGame(pt)
print(g4)

2-player NormalFormGame with payoff profile array:
[[[-100,  -50],  [-200,    0],  [-200,    0],  [-200,    0],  [-200,    0],  [-200,    0],  [-200,    0]],
 [[   0, -100],  [ -75,  -25],  [-150,    0],  [-150,    0],  [-150,    0],  [-150,    0],  [-150,    0]],
 [[   0, -100],  [   0,  -50],  [ -50,    0],  [-100,    0],  [-100,    0],  [-100,    0],  [-100,    0]],
 [[   0, -100],  [   0,  -50],  [   0,    0],  [ -25,   25],  [ -50,    0],  [ -50,    0],  [ -50,    0]],
 [[   0, -100],  [   0,  -50],  [   0,    0],  [   0,   50],  [   0,   50],  [   0,    0],  [   0,    0]],
 [[   0, -100],  [   0,  -50],  [   0,    0],  [   0,   50],  [   0,  100],  [  25,   75],  [  50,    0]],
 [[   0, -100],  [   0,  -50],  [   0,    0],  [   0,   50],  [   0,  100],  [   0,  150],  [  50,  100]]]


In [ ]:
def sequential_best_response(g, init_actions=None, tie_breaking='smallest',
                             verbose=True):
    """
    Find a pure Nash equilibrium of a normal form game by sequential best
    response.

    Parameters
    ----------
    g : NormalFormGame

    init_actions : array_like(int), optional(default=[0, ..., 0])
        The initial action profile.

    tie_breaking : {'smallest', 'random'}, optional(default='smallest')

    verbose: bool, optional(default=True)
        If True, print the intermediate process.

    """
    N = g.N  # Number of players
    a = np.empty(N, dtype=int)  # Action profile
    if init_actions is None:
        init_actions = [0] * N
    a[:] = init_actions

    if verbose:
        print('init_actions: {0}'.format(a))

    new_a = np.empty(N, dtype=int)
    max_iter = np.prod(g.nums_actions)

    for t in range(max_iter):
        new_a[:] = a
        for i, player in enumerate(g.players):
            if N == 2:
                a_except_i = new_a[1-i]
            else:
                a_except_i = new_a[np.arange(i+1, i+N) % N]
            new_a[i] = player.best_response(a_except_i,
                                            tie_breaking=tie_breaking)
            if verbose:
                print('player {0}: {1}'.format(i, new_a))
        if np.array_equal(new_a, a):
            return a
        else:
            a[:] = new_a

    print('No pure Nash equilibrium found')
    return None

In [ ]:
import numpy as np
import quantecon.game_theory as gt

In [ ]:
a_star = sequential_best_response(g4)  # By default, start with (0, 0, 0)
print('Nash equilibrium indices: {0}'.format(a_star))

init_actions: [0 0]
player 0: [1 0]
player 1: [1 2]
player 0: [3 2]
player 1: [3 3]
player 0: [4 3]
player 1: [4 3]
player 0: [4 3]
player 1: [4 3]
Nash equilibrium indices: [4 3]


In [ ]:
سgt.support_enumeration(g4)

[(array([0., 0., 0., 0., 1., 0., 0.]), array([0., 0., 0., 1., 0., 0., 0.])),
 (array([0., 0., 0., 0., 1., 0., 0.]), array([0., 0., 0., 0., 1., 0., 0.])),
 (array([0., 0., 0., 0., 0., 1., 0.]), array([0., 0., 0., 0., 1., 0., 0.]))]